sudo: required
services:
  - docker


before_install:
  - docker build -t austinchappell/docker-practice -f Dockerfile.dev .

script:
  - docker run austinchappell/docker-practice yarn test --watchAll=false --coverage