sudo: required
services:
  - docker


before_install:
  - docker build -t austinchappell/docker-practice -f Dockerfile.dev .

script:
  - docker run -e CI=true austinchappell/docker-practice yarn test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-practice"
  env: "DockerPractice-env"
  bucket_name: "elasticbeanstalk-us-east-1-160429721193"
  bucket_path: "docker-practice"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"